const PIECES = [
  {
    ref: "ROU-001",
    nom: "vario",
    categorie: "variation",
    modele: "Yamaha Nitro/booster",
    etat: "Occasion",
    prix: 30,
    compatible: "Nitro / Aerox/booster",
    photo: "https://i.postimg.cc/zvhzcNcV/B6B53B11-E55B-455B-8BB3-8D84C16FA588.png",
    vendu: true
  },
  {
    ref: "",
    nom: "embrayage",
    categorie: "variation",
    modele: "MBK Booster",
    etat: "Occasion",
    prix: 50,
    compatible: "Booster 2004+",
    photo: "",
    vendu: false
  },
  {
    ref: "",
    nom: "boite a clapet",
    categorie: "variation",
    modele: "MBK Booster",
    etat: "Occasion",
    prix: 10,
    compatible: "Booster 2004+",
    photo: "https://i.postimg.cc/L4T0jLW1/4396FF43-0F8C-4CA1-8896-AF7291C0C926.png",
    vendu: false
  },
  {
    ref: "",
    nom: "transmission",
    categorie: "moteur",
    modele: "MBK Booster",
    etat: "Occasion",
    prix: 40,
    compatible: "MBK Booster",
    photo: "https://i.postimg.cc/kMxTqK9d/9E778C9E-DD18-4E16-BE45-40E63313A230.png",
    vendu: false
  },
  {
    ref: "SCO-001",
    nom: "MBK Nitro",
    categorie: "Scooter complet",
    modele: "MBK Booster",
    etat: "Prêt à rouler",
    prix: 1500,
    compatible: "Démarre au quart de tour, pneus récents, papiers en ordre",
    photo: "https://i.postimg.cc/02gHrLvP/att-q-Jv-TYJ4Ew-FAJVZBs-JNiz-N4j0m-GTf-B1D92-No-Sz-AK-w.jpg",
    vendu: true
  },
  {
    ref: "SCO-003",
    nom: "MBK Booster Spirit 2012",
    categorie: "Scooter complet",
    modele: "MBK Booster",
    etat: "Prêt à rouler",
    prix: 2000,
    compatible: "Démarre au quart de tour, pneus récents, papiers en ordre",
    photo: "https://i.postimg.cc/xdrrQcdQ/att-SBz-CSf7Sc-Xtkk-KZMo-Dq-EQ-v-6g-JI5H3YTu5u-Tn-Utc-Y.jpg",
    vendu: false
  },
  {
    ref: "SCO-004",
    nom: "MBK Booster Spirit 2006",
    categorie: "Scooter complet",
    modele: "MBK Booster",
    etat: "Prêt à rouler",
    prix: 1500,
    compatible: "Démarre au quart de tour, pneus récents, papiers en ordre",
    photo: "https://i.postimg.cc/RZwLJ8Xg/att-w-SMzp-X9HEZ01LLKt-zm9Pm-M1UZDWMd-S-QW-4Haa5CY.jpg",
    vendu: true
  },
  {
    ref: "SCO-002",
    nom: "Honda Wallaroo",
    categorie: "Scooter complet",
    modele: "Yamaha Nitro",
    etat: "À réparer",
    prix: 700,
    compatible: "Moteur tourne, carbu à nettoyer, frein avant à revoir",
    photo: "https://i.postimg.cc/ryHrqk5P/att-IFQKl87-RBHi-X1mm5b4Exv2Nxj-HZGtt-TEAt-QDOj6DSQ.jpg",
    vendu: false
  },
  {
    ref: "5BR-F4710-00",
    nom: "Selle Nitro",
    categorie: "Carrosserie",
    modele: "Yamaha Nitro",
    etat: "Occasion",
    prix: 35,
    compatible: "Nitro / Aerox",
    photo: "https://i.postimg.cc/d3pH9CMY/att-s-XUTVussl-Lh-Oqw9u-2la-WCs-Phe-V53gz-CP0UNPOT8Cw.jpg",
    vendu: false
  },
  {
    ref: "5BR-F4730-00",
    nom: "Selle Booster",
    categorie: "Carrosserie",
    modele: "MBK Booster",
    etat: "Occasion",
    prix: 40,
    compatible: "Booster 2004+",
    photo: "https://i.postimg.cc/zBnKQRR3/att-k-Mz0xz6cgghd-OIVayjx-Dodbx-TB5MHMVyl-Ase-Ks8YOE.jpg",
    vendu: false
  },
  {
    ref: "CAR-001",
    nom: "Compteur",
    categorie: "Carrosserie",
    modele: "Yamaha Nitro",
    etat: "Occasion",
    prix: 80,
    compatible: "Yamaha Nitro",
    photo: "https://i.postimg.cc/8PY3hZqb/1D38D209-F2A1-4338-9F69-F4529A89F8BA.jpg",
    vendu: false
  },
  {
    ref: "",
    nom: "cable frein",
    categorie: "cablage",
    modele: "MBK Booster",
    etat: "neuf",
    prix: 10,
    compatible: "Booster",
    photo: "https://i.postimg.cc/L8n4ZzHf/IMG-1205.jpg",
    vendu: false
  },
  {
    ref: "TRA-001",
    nom: "Carbu 21 Motorforce",
    categorie: "Moteur",
    modele: "Universel",
    etat: "Occasion",
    prix: 50,
    compatible: "Universel",
    photo: "https://i.postimg.cc/J4b4SVxz/att-RRLf8Jzdq1dl-RM-Cl4oz30x-Y3Gusrj-W3Bp-Zlgb-Mp93A.jpg",
    vendu: false
  },
  {
    ref: "ELE-001",
    nom: "Faisceau électrique complet",
    categorie: "cablage",
    modele: "MBK Booster",
    etat: "Occasion",
    prix: 50,
    compatible: "Booster",
    photo: "https://i.postimg.cc/1zCPGWz0/att-KOb6b2tp-D6Fn-Y6mq2JRx-Iw3Ettc-UJWFKj-MDQhhdlaao.jpg",
    vendu: false
  },
  {
    ref: "FIC-001",
    nom: "Pot d'échappement sport",
    categorie: "Moteur",
    modele: "MBK Booster",
    etat: "Occasion",
    prix: 60,
    compatible: "Booster / Stunt",
    photo: "",
    vendu: false
  },
  {
    ref: "FIC-002",
    nom: "Pneu arrière 130/70-13",
    categorie: "Roues & Pneus",
    modele: "Yamaha Nitro",
    etat: "Neuf",
    prix: 45,
    compatible: "Nitro / Aerox",
    photo: "",
    vendu: false
  },
  {
    ref: "FIC-003",
    nom: "Kit plastiques carénage complet",
    categorie: "Carrosserie",
    modele: "MBK Booster",
    etat: "Occasion",
    prix: 120,
    compatible: "Booster 2004+",
    photo: "",
    vendu: false
  },
  {
    ref: "FIC-004",
    nom: "Disque de frein avant",
    categorie: "Freinage",
    modele: "Yamaha Nitro",
    etat: "Neuf",
    prix: 25,
    compatible: "Nitro / Aerox",
    photo: "",
    vendu: false
  },
  {
    ref: "FIC-005",
    nom: "Rétroviseurs paire",
    categorie: "Accessoires",
    modele: "Universel",
    etat: "Neuf",
    prix: 15,
    compatible: "Universel",
    photo: "",
    vendu: false
  },
  {
    ref: "FIC-006",
    nom: "Bougie d'allumage",
    categorie: "Moteur",
    modele: "Universel",
    etat: "Neuf",
    prix: 5,
    compatible: "Universel 2 temps",
    photo: "",
    vendu: false
  },
  {
    ref: "FIC-007",
    nom: "Clignotants avant/arrière",
    categorie: "Électrique",
    modele: "MBK Booster",
    etat: "Occasion",
    prix: 20,
    compatible: "Booster 2004+",
    photo: "",
    vendu: false
  },
  {
    ref: "FIC-008",
    nom: "Béquille centrale",
    categorie: "Accessoires",
    modele: "Peugeot Ludix",
    etat: "Occasion",
    prix: 18,
    compatible: "Ludix",
    photo: "",
    vendu: false
  },
  {
    ref: "FIC-009",
    nom: "Poignée de gaz + câble",
    categorie: "cablage",
    modele: "Yamaha Nitro",
    etat: "Neuf",
    prix: 12,
    compatible: "Nitro / Aerox",
    photo: "",
    vendu: false
  },
  {
    ref: "FIC-010",
    nom: "Filtre à air sport",
    categorie: "Moteur",
    modele: "MBK Booster",
    etat: "Neuf",
    prix: 22,
    compatible: "Booster / Stunt",
    photo: "",
    vendu: false
  }
];
